### ISSUE TITLE
Progress tracker

### ISSUE THREAD

**Issue by AndrewRathbun** [EZToolsManuals/EZToolsManuals#1]
CLI Tools

 - [x] amcacheparser - TODO for understanding the artifact
 - [x]  appcompatcacheparser - substantial completion
 - [ ] bstrings - started 8/8/2022
 - [ ] evtxecmd - started 8/8/2022
 - [x] iisgeolocate
 - [x] jlecmd
 - [x] lecmd
 - [ ] mftecmd - started 8/8/2022
 - [x] pecmd - need to finish switch descriptions
 - [x] rbcmd
 - [ ] recentfilecacheparser - references, example commands, switches done
 - [ ] recmd - started 8/4/2022
 - [x] rla
 - [x] sbecmd - substantial completion
 - [ ] sqlecmd - started 8/8/2022
 - [x] srumecmd
 - [x] sumecmd - done except for sample output and key takeaways
 - [x] vscmount
 - [x] wxtcmd

GUI Tools

 - [x] ezviewer
 - [ ] jumplistexplorer
 - [ ] mftexplorer
 - [x] registryexplorer
 - [ ] sdbexplorer
 - [x] shellbagsexplorer
 - [ ] timelineexplorer
